Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
bw = BayesRegression(df=df, y='isi', treatment='stim', condition='neuron', group='mouse', )
bw.plot(x='stim').facet('neuron')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_8074/1807159905.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mbw[0m [0;34m=[0m [0mBayesRegression[0m[0;34m([0m[0mdf[0m[0;34m=[0m[0mdf[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;34m'isi'[0m[0;34m,[0m [0mtreatment[0m[0;34m=[0m[0;34m'stim'[0m[0;34m,[0m [0mcondition[0m[0;34m=[0m[0;34m'neuron'[0m[0;34m,[0m [0mgroup[0m[0;34m=[0m[0;34m'mouse'[0m[0;34m,[0m [0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mbw[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mx[0m[0;34m=[0m[0;34m'stim'[0m[0;34m)[0m[0;34m.[0m[0mfacet[0m[0;34m([0m[0;34m'neuron'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bayes_window/slopes.py[0m in [0;36mplot[0;34m(self, x, color, detail, independent_axes, add_data, **kwargs)[0m
[1;32m    130[0m             [0madd_data[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mwindow[0m[0;34m.[0m[0madd_data[0m[0;34m[0m[0;34m[0m[0m
[1;32m    131[0m         [0;32mif[0m [0madd_data[0m [0;32mor[0m [0mself[0m[0;34m.[0m[0mposterior[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m  [0;31m# LME[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 132[0;31m             [0mposterior[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mdata_and_posterior[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    133[0m         [0;32melif[0m [0;34m'slope_per_condition'[0m [0;32min[0m [0mself[0m[0;34m.[0m[0mposterior[0m[0;34m.[0m[0mkeys[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    134[0m             [0mposterior[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mposterior[0m[0;34m[[0m[0;34m'slope_per_condition'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'BayesRegression' object has no attribute 'data_and_posterior'
AttributeError: 'BayesRegression' object has no attribute 'data_and_posterior'

